### ISSUE TITLE
Error: Invalid name: "@p2olab/polaris-backend"

### ISSUE THREAD

**Issue by andy778** [p2o-lab/polaris-backend#129]
**running npm install returns error**
if I remove characters "@" and  "/" in name i can continue

**To Reproduce**
$ npm install
npm ERR! Error: Invalid name: "@p2olab/polaris-backend"
npm ERR!     at ensureValidName (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:284:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/lib/nodejs/normalize-package-data/lib/fixer.js:199:5)
npm ERR!     at /usr/lib/nodejs/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/lib/nodejs/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/lib/nodejs/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/lib/nodejs/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/lib/nodejs/read-package-json/read-json.js:299:40
npm ERR!     at fs.js:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
npm ERR! System Linux 3.13.0-52-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/devel/polaris-backend
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10

**It's the regex in match that triggers **

function ensureValidName (name, strict) {
  if (name.charAt(0) === "." ||
      name.match(/[\/@\s\+%:]/) ||
      name !== encodeURIComponent(name) ||
      (strict && name !== name.toLowerCase()) ||
      name.toLowerCase() === "node_modules" ||
      name.toLowerCase() === "favicon.ico") {
        throw new Error("Invalid name: " + JSON.stringify(name) )
  }
}

**Comment by andy778** [comment]
Updated my virtual engine to ubuntu 19.10 and then it worked as there was newer nodejs and npm
